builds:
- env:
  - CGO_ENABLED=0
  binary: gomake
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    - arm64

archives: 
  format: binary

dockers:
- image_templates:
  - "fasibio/gomake:{{ .Version }}-amd64"
  use: buildx
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/amd64"
- image_templates:
  - "fasibio/gomake:{{ .Version }}-arm64v8"
  use: buildx
  goarch: arm64
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/arm64/v8"
docker_manifests:
- name_template: fasibio/gomake:{{ .Version }}
  image_templates:
  - fasibio/gomake:{{ .Version }}-amd64
  - fasibio/gomake:{{ .Version }}-arm64v8
