builds:
  - goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
dockers:
  - image_templates:
    - fasibio/gomake
release:
  furies:
    - account: myaccount
  github: